title: PicPocket Dev Documentation
description: PicPocket Dev Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  PicPocket Repository: https://github.com/ChadWKirk/PicPocket
